BUTTON_TO_DYNAMIC_TABLE_PAGE = "text=Dynamic Table Test Page"
DYNAMIC_TABLE_DATA_BUTTON = "text=Table Data"
DYNAMIC_TABLE_DATA = "#dynamictable > tr > td"
DYNAMIC_EMPTY_TABLE = "#dynamictable > tr"
TEXTAREA_FOR_TABLE = "textarea"
TABLE_CAPTION_NAME = "text=Caption: >> input[type='text']"
TABLE_NAME = "caption:has-text('Table')"
TABLE_CAPTION_ID = "text=Id: >> input[type='text']"
TABLE_ID = "//*[@id='tablehere']//*[@id]"
REFRESH_TABLE_DATA = "text=Refresh Table"
