BUTTON_TO_FAKE_ALERT_PAGE = "text=Fake Alerts"
ALERT_BOX_BUTTON = "text=Show alert box"
ACCEPT_BUTTON = "text=OK"
MODAL_BOX_BUTTON = "text=Show modal dialog"
# ACCEPT_MODAL_BOX_BUTTON = "text=OK"
ALERT_BOX = "//*[@id='dialog-text']"
